config/routes.rb
AcrossEc::Application.routes.draw do

  resources :deadlines

  get "registration_confirmation/new"

  get "password_resets/new"

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/privacy"
  
  get "pages/question"

  root :to => 'pages#home'
 
  match '/loginasregistrar', :to => 'sessions#new'
  match '/loginasstudent', :to => 'sessions_students#new'
  match '/registrarlogout', :to => 'sessions#destroy'
  match '/studentlogout', :to => 'sessions_students#destroy'
  match '/applications/:id/approve', :to => 'applications#approve'
  match '/applications/:id/decline', :to => 'applications#decline'
  match '/students/:id/resend_confirmation', :to => 'students#resend_confirmation'
  match '/login', :to => 'pages#login'
  match '/confirm/:id/:code', :to => 'students#confirm_account'

  resources :universities
  resources :schedules
  resources :sessions
  resources :registrars
  resources :students
  resources :sessions_students
  resources :applications
  resources :password_resets

end

app/models/registrar.rb
class Registrar < ActiveRecord::Base

	has_secure_password
  validates_presence_of :password, :on => :create

  attr_accessible :email, :first_name, :last_name, :phone, :password, :password_confirmation, :admin, :university_id
  has_many :schedules
  belongs_to :university
  validates :first_name, :last_name, :email, :phone, :presence => true
   validates_format_of :first_name, :with => /^[a-z A-Z -']+$/, :message => "Invalid Name"
  validates_format_of :last_name, :with => /^[a-z A-Z \- -']+$/, :message => "Invalid Name"
  validates_format_of :email, :with => /^[\w]([^@\s,;]+)@(qatar\.|qatar-med\.)?(cmu|vcu|tamu|georgetown|cornell)\.(edu)$/i, :message => "not vaild email" # method to limit users to only enter university email id
  validates_format_of :phone, :with => /^(\+?\d{8}|\+?\d{3}?[-.]\d{4}?[-.]\d{4})$/, :message => "should be 11 digits (country code needed)" # method to only enter 8 digit phone number
  
  def proper_name # method to get the full name of user
    first_name + " " + last_name
  end

end

app/controllers/registrars_controller.rb
class RegistrarsController < ApplicationController
  # GET /registrars
  # GET /registrars.json
  load_and_authorize_resource #authorization code to limit access to controller actions, to avoid url hacking
  def index
    @title = "Registrars"
    @registrars = Registrar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registrars }
    end
  end

  # GET /registrars/1
  # GET /registrars/1.json
  def show
    @title = "Registrar"
    @registrar = Registrar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registrar }
    end
  end

  # GET /registrars/new
  # GET /registrars/new.json
  def new
    @title = "Create New Registrar"
    @registrar = Registrar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registrar }
    end
  end

  # GET /registrars/1/edit
  def edit
    @title = "Editing Registrar"
    @registrar = Registrar.find(params[:id])
  end

  # POST /registrars
  # POST /registrars.json
  def create
    @registrar = Registrar.new(params[:registrar])

    respond_to do |format|
      if @registrar.save
        session[:registrar_id] = @registrar.id
        format.html { redirect_to @registrar, notice: 'Registrar was successfully created.' }
        format.json { render json: @registrar, status: :created, location: @registrar }
      else
        format.html { render action: "new" }
        format.json { render json: @registrar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /registrars/1
  # PUT /registrars/1.json
  def update
    @registrar = Registrar.find(params[:id])

    respond_to do |format|
      if @registrar.update_attributes(params[:registrar])
        format.html { redirect_to @registrar, notice: 'Registrar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registrar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrars/1
  # DELETE /registrars/1.json
  def destroy
    @registrar = Registrar.find(params[:id])
    @registrar.destroy

    respond_to do |format|
      format.html { redirect_to registrars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/registrars_helper.rb
module RegistrarsHelper
end

app/views/registrars/_form.html.erb
<%= form_for(@registrar) do |f| %>
  <% if @registrar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registrar.errors.count, "error") %> prohibited this registrar from being saved:</h2>

      <ul>
      <% @registrar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>
<br>
<div class="student_table">

   <h1>New Registrars</h1>


  <div class="field">
	
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :university_id %><br />
    <%= collection_select(:registrar, :university_id, University.all, :id, :name) %><br />
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div> 

app/views/registrars/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @registrar %> |
<%= link_to 'Back', registrars_path %>

app/views/registrars/index.html.erb
<br>
<br>
<br>
<br>
<br>

<table class="gridtable">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone</th>

  </tr>

<% @registrars.each do |registrar| %>
  <tr>
    <% if current_registrar != 0 || registrar.admin == false || current_registrar.admin == true %>
    <% if current_student  != 0 && registrar.admin == false %>
    <td><%= registrar.first_name %></td>
    <td><%= registrar.last_name %></td>
    <td><%= registrar.email %></td>
    <td><%= registrar.phone %></td>
    <td><%= link_to "Show", registrar %></td>
    <% if can? :update, @registrar %>
      <td><%= link_to "Edit", edit_registrar_path(registrar) %></td>
    <% end %>
    <% if can? :destroy, @registrar %>
    <td><%= button_to "delete", registrar, :method => :delete %></td>
    <% end %>
    <% end %>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if can? :create, @registrar %>
<%= link_to 'New Registrar', new_registrar_path %>
<% end %>

app/views/registrars/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', registrars_path %>

app/views/registrars/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<br> <br> <br> <br> <br> 

<div class="show_table"> 

<h1> Show Registrar Information </h1> 

<p>
  <b>First name:</b>
  <%= @registrar.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @registrar.last_name %>
</p>

<p>
  <b>University:</b>
  <% temp = @registrar.university_id %>
  <%= University.find(temp).name %>
</p>

<p>
  <b>Email:</b>
  <%= @registrar.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @registrar.phone %>
</p>

<% if can? :update, @registrar %>
	<%= link_to 'Edit', edit_registrar_path(@registrar) %> |
<% end %>
<%= link_to 'Back', registrars_path %>


</div> 