config/routes.rb
AcrossEc::Application.routes.draw do

  resources :deadlines

  get "registration_confirmation/new"

  get "password_resets/new"

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "pages/privacy"
  
  get "pages/question"

  root :to => 'pages#home'
 
  match '/loginasregistrar', :to => 'sessions#new'
  match '/loginasstudent', :to => 'sessions_students#new'
  match '/registrarlogout', :to => 'sessions#destroy'
  match '/studentlogout', :to => 'sessions_students#destroy'
  match '/applications/:id/approve', :to => 'applications#approve'
  match '/applications/:id/decline', :to => 'applications#decline'
  match '/students/:id/resend_confirmation', :to => 'students#resend_confirmation'
  match '/login', :to => 'pages#login'
  match '/confirm/:id/:code', :to => 'students#confirm_account'

  resources :universities
  resources :schedules
  resources :sessions
  resources :registrars
  resources :students
  resources :sessions_students
  resources :applications
  resources :password_resets

end

app/views/pages/about.html.erb
<div id="section3"> 
<h3>Our Mission: </h3> 
<p>Simpletech aims to provide a better, more efficient way for students to register for courses in other universities, through AcrossEC. 
</p> 

<h3>AcrossEC: </h3>
<p>AcrossEC is a web application that provides a platform for students and registrars to facilitate the cross registration process. <p> 

<p>Students are able to signup and apply for courses, after viewing different schedules from different universities in Education City. Students are also able to check the status of the application through AcrossEC. </p> 

<p>Registrars are able to upload different class schedules associated with their universities. They are also able to view student applications that are sent to their universities. In addition, Registrars can approve or decline applications through AcrossEC with an automatic notifications to students who applied. </p> 

<h3>Simpletech: </h3>

<p> Simpletech is a team of Information Systems juniors, at Carnegie Mellon University in Qatar. Our team consists of: </p> 

<p>
Hawra Abdulla <br>
Nawal Behih<br>
Talal Shoeb<br>
Zuhair Ghalib
</p>
</div> 

app/views/pages/contact.html.erb
<br><br><br><br>
<div class="show_table"> 
<h3>Contact Us</h3>

<p>Simpletech</p>
<p>Telephone: +974 66177975</p>
<p>Address: 1173 Carnegie Mellon University, Education City. Doha, Qatar </p>
<p>If you have any Questions or Comments please email us at</p> <a href="mailto:across.ec@gmail.com">Across.EC@gmail.com</a>
</div>  

app/views/pages/home.html.erb
<div id="mapimage">
<img src="http://i36.tinypic.com/2en3wcy.jpg" alt="EC Map" width="600" height="350">
</div>

<div id="first_column_down">
<h3> Important Deadlines </h3> 
<% @deadline = Deadline.all[0] %>
<p> Semester:
<%= @deadline.semester %>
</p>
<p>
Start of registration:
<%= @deadline.start_of_registration %>
</p>
<p>
Start of classes:
<%= @deadline.start_of_classes %>
</p>

<% if current_registrar %>
<% if current_registrar.admin == true %>
<li><a href="/deadlines/1/edit">Update Deadlines</a></li>
<% end %>
<% end %>
</div>

<div class="first_column">

<h2> Welcome to Across EC </h2>
<p class"overlay-text"> 
Across EC is an online cross registration website done by SimpleTech, a group of students from Carnegie Mellon University in Qatar. This website allows its users to look at the courses offered in Education City Universities, register for a given course as a student and check out all the applications and chose which ones to approve and which ones to decline as a registrar.</p>
<p>This website is easy to use and will save a lot of your time. Enjoy it!</p>
<br /><br /><br /><br />
</div>

app/views/pages/login.html.erb

                           
                    <%= form_tag sessions_students_path do %>
                             
                            <div id="second_column">
                             <div id="first_logS">
                                        <div class="login">
                                          <h1>Students log in</h1>
                                          <%= label_tag :email %>
                                          <br />
                                          <%= text_field_tag :email, params[:email] %>
                                          <div class="field">
                                          <%= label_tag :password %>
                                          <%= password_field_tag :password %>
                                          </div>
                                          <div class="actions"><%= submit_tag "Log in"%></div>
                                          </div> 
                                      	</div>
                              </div>
                     <% end %>

              
  


        <%= form_tag sessions_path do %>
                  <div id="second_column">
                                 <div id="second_logR">
                                                <div class="login">
                                              	   <h1>Registrars log in</h1>
                                                  <%= label_tag :email %>
                                              <br>
                                                 <%= text_field_tag :email, params[:email] %>
                                            <div class="field">
                                         <%= label_tag :password %>
                                              <%= password_field_tag :password %>
                                          <div class="actions"><%= submit_tag "Log in" %></div>
                                              </div>
                                              	</div>
                                  </div>
                        </div> 
        <% end %>



<div class="sign_forg">
<p><%= link_to "forgotten password?", new_password_reset_path %></p>
        <div id="Signup">

            <p> Don't have an account? <%= link_to "Sign Up", new_student_path %> </p>
          </div>
</div>

app/views/pages/loginin.html.erb


<%= form_tag sessions_students_path do %>
<div id="second_column">
  <div class="login">
    <h1>Log in as a Student</h1>
    <%= label_tag :email %>
<br />
    <%= text_field_tag :email, params[:email] %>
      <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
   <div class="actions"><%= submit_tag "Log in" %></div>
<div id="Signup">
<br><br>
    <p> Don't have an account? <%= link_to "Sign Up", new_student_path %> </p>
  </div>
</div>


</div>
 


<% end %>


app/views/pages/privacy.html.erb
<div id="section1"> 

<h1>Privacy Policy</h1>

<p>This Privacy Policy governs the manner in which AcrossEC collects, uses, maintains and discloses information collected from users of the www.across-ec.herokuapp.com website. This privacy policy applies to the Site and all products and services offered by AcrossEC.
</p>

<h3>Personal identification information</h3>

<p>We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users register on the site, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, phone number. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.
</p>

<h3>Non-personal identification information</h3>

<p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.</p>

<h3>Web browser cookies</h3>

<p> Our Site may use "cookies" to enhance User experience. User's web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly. </p> 

<h3>How we use collected information </h3>

<p> AcrossEC may collect and use Users personal information for the following purposes:

- To process applications
We may use the information Users provide about themselves when applying for a course. We do not share this information with outside parties except to the extent necessary to provide the service.

- To send periodic emails
We may use the email address to respond to their inquiries, questions, and/or other requests. 
</p>
</div> 

<div id="section2"> 
<h3>How we protect your information</h3>

<p>We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password and data stored on our Site.

Sensitive and private data exchange between the Site and its Users happens over a SSL secured communication channel and is encrypted and protected with digital signatures.
</p>

<h3>Sharing your personal information</h3>

<p>We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.</p> 

<h3>Changes to this privacy policy</h3>

<p> AcrossEC has the discretion to update this privacy policy at any time. When we do, we will send you an email. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications. </p>

<h3>Your acceptance of these terms</h3>

<p>By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.
</p> 


<h3>Contacting us</h3>

<p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:
AcrossEC
www.across-ec.herokuapp.com
across.ec@gmail.com
</p> 

</div> 